-- migrate:up
SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE product MODIFY id INT NOT NULL AUTO_INCREMENT;
ALTER TABLE product_info MODIFY id INT NOT NULL AUTO_INCREMENT;
ALTER TABLE payments MODIFY id INT NOT NULL AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS=1;
-- migrate:down

